# Generated by Django 5.1.7 on 2025-03-17 10:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0003_alter_customerprofile_user_bookingdetails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingDetails',
            new_name='Booking',
        ),
    ]
